### ISSUE TITLE
アドオン有効時にエラーなる

### ISSUE THREAD

**Issue by culage** [nepia11/Blender-AnimeHairSupporter#3]
アドオンのフォルダ名にドットが入っているとアドオン有効時にエラーになってしまいました。
![err](https://user-images.githubusercontent.com/5794025/105842773-1274e900-601a-11eb-8011-47b1820ac0de.png)

Blender-AnimeHairSupporter-hotfix-2.9x→Blender-AnimeHairSupporter-hotfix-29xに変更して試すとうまくいきました。
blender-2.91.0で発生した現象なので、もしかすると現在の2.91.2だと問題ないのかもしれません。

**Comment by nepia11** [comment]
とりあえずピリオドを含まないブランチ名で切り直しておきます

**Comment by nepia11** [comment]
https://github.com/nepia11/Blender-AnimeHairSupporter/tree/29x
ピリオドを含まないブランチ名で切り直しました
以後2.9x向けの変更はこちらに反映していきます
